name: MLflow CI Workflow

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 pandas scikit-learn

    - name: Run mlflow project
      run: |
        mlflow run MLProject --experiment-name "CI_Retraining" --env-manager local
      
    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        # Mengambil RUN_ID menggunakan script python agar lebih akurat
        RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs(experiment_names=['CI_Retraining']).iloc[0]['run_id'])")
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Found Run ID: $RUN_ID"

    - name: Build Docker Model
      run: |
        # Menggunakan mlflow models build-docker dengan RUN ID yang benar
        mlflow models build-docker -m runs:/${{ env.RUN_ID }}/model -n arielhebron/credit-risk-model:latest --install-mlflow

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker Image
      run: |
        docker tag arielhebron/credit-risk-model:latest arielhebron/credit-risk-model:${{ github.sha }}

    - name: Push Docker Image
      run: |
        docker push arielhebron/credit-risk-model:latest
        docker push arielhebron/credit-risk-model:${{ github.sha }}

    - name: Complete job
      run: echo "Workflow CI Complete"
